name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to the GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GHCR_USER }}
      #     password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: false
          context: .
          file: ./Containerfile
          tags: |
            ghcr.io/afrossard/${{ github.workflow }}:latest
            ghcr.io/afrossard/${{ github.workflow }}:${{ github.sha }}
